project:
  type: website

website:
  title: "GEO511 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: zephyr
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    toc-location: left-body
    includes:
        after_body: include/after_body.html
    bibliography: data/GEO511FinalProject.bib
